### ISSUE TITLE
rerun territoriality and sociality

### ISSUE THREAD

**Issue by vjjan91** [vjjan91/diurnal-Acoustics#6]
Hi @PaviS0102 - I have pushed changes and updates. Can you rerun the 05 and )6 and push results? We can get on a call with Laurel tomorrow about the same.

**Comment by PaviS0102** [comment]
Sure, that sounds good, Vijay!

**Comment by vjjan91** [comment]
Wondering if we should move to ggstatsplot for the figures (see script 07 (pushed just now)? Upto you - just a thought

**Comment by vjjan91** [comment]
@PaviS0102 I think the terriotriality and sociality scripts need to be comparing within category but across dawn and dusk - I don't think we care if there are differences within the same 'time_of_day' - we want to know if there are differences between dawn and dusk for highly territorial, and so on. Does that make sense? Check out the push I did just now for script 07.

**Comment by PaviS0102** [comment]
Oh, yes, Vijay, I just checked the trophic niche figure. Yes, I am up for
it- maybe we could discuss it tomorrow because I don't understand it fully.

Oh, so you mean the expectation would be that highly territorial species
have a higher vocal activity at dawn than dusk?

**Comment by vjjan91** [comment]
Yup - the idea here is that our comparisons ultimately are between dawn and dusk.

Now, we are asking if territoriality plays a role in differences between vocal activity between dawn and dusk. 

I am happy to quickly run it - no worries!

**Comment by PaviS0102** [comment]
Got it- running it now! That's fine- I could do it- don't worry. I will make a push soon!

**Comment by vjjan91** [comment]
Oops, hold on - I just made a push

**Comment by vjjan91** [comment]
Pushed changes - please edit/make changes accordingly. I would love your suggestions on other ways we could explore the data. The thing that remains to be done is the PGLS analysis - would you like to lead it/explore the same? @PaviS0102

**Comment by PaviS0102** [comment]
Sure, Vijay, thanks for this! Yes, I would love to explore PGLS analysis-
would be super exciting! Will get started on it asap! :D

**Comment by vjjan91** [comment]
Thanks @PaviS0102! Appreciate it - and sorry I jumped in and edited it before I could communicate the changes! Will await your edits/code for the PGLS. 

I found the metadata from the Mikula et al. 2021 paper a useful reference for PGLS (see `fit_phylolm.R` script here - https://osf.io/fa9ky/
